dataset_path: "/archive/zhuchunzheng/RIQA-US/dataset0"
device: "cuda"
num_workers: 0
img_size: 224
experiment_name: "Reg2IQA"
vis_samples: False
mode: "rotation_scale"
lr: 0.0001
momentum: 0.9
epochs: 600
trn_batch_size: 4
val_batch_size: 2



