dataset_path: "**" # Set the dataset path
device: "cuda"
num_workers: 0
img_size: 224
experiment_name: "RIQA-US"
vis_samples: False
mode: "rotation_scale"
lr: 0.0001
momentum: 0.9
epochs: 500
trn_batch_size: 4
val_batch_size: 2



